### ISSUE TITLE
Regression: error while testing on an url

### ISSUE THREAD

**Issue by groar** [Deepomatic/DIGITS#19]
I tried to test a model on the following url: [http://upload.wikimedia.org/wikipedia/commons/7/7d/Thorsberg_Shields.jpg](http://upload.wikimedia.org/wikipedia/commons/7/7d/Thorsberg_Shields.jpg)

I got the following error:
```
500: INTERNAL SERVER ERROR
LoadImageError
cannot identify image file <cStringIO.StringI object at 0x7f3c2052f360>

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/groar/DEEPOMATIC-DIGITS/digits/model/images/regression/views.py", line 239, in image_regression_model_classify_one
    image = utils.image.load_image(flask.request.form['image_url'])
  File "/home/groar/DEEPOMATIC-DIGITS/digits/utils/image.py", line 52, in load_image
    raise errors.LoadImageError, e.message
LoadImageError: cannot identify image file 
```

**Comment by groar** [comment]
But it works with [http://www.valyriansteel.com/shop/images/uploads/Shield%20back%20with%20Arm.jpg](http://www.valyriansteel.com/shop/images/uploads/Shield%20back%20with%20Arm.jpg)

**Comment by groar** [comment]
Seems to work now...
